# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_matrix:
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-12, windows-latest]
    runs-on: ${{ matrix.os }}
    env:
      app_name: app_${{ matrix.os }}_${{ github.run_number }}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Build
        run: g++ hello.cpp -o ${{ env.app_name }}
      
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact-matrix
          path: ${{ env.app_name }}**
          retention-days: 5

    



